title: ZidaLab Wiki
description: Lab Guide for ZidaLab members
theme: just-the-docs

url: https://zidalab.github.io/lab_wiki

aux_links:
  ZidaLab: https://zidalab.github.io

nav:
  - title: Home
    url: /
  - title: Meeting
    url: /docs/meeting
  - title: Experiment
    url: /docs/experiment
  - title: Writing
    url: /docs/writing
