title: ZidaLab Wiki
description: Lab Guide for ZidaLab members
theme: just-the-docs

url: https://zidalab.github.io/lab_wiki

aux_links:
  ZidaLab: https://zidalab.github.io

nav:
  - title: Home
    url: /
  - title: 开会
    url: /docs/meeting
  - title: 实验
    url: /docs/experiment
  - title: 写作与画图
    url: /docs/writing
  - title: 培训
    url: /docs/training
  - title: 其他
    url: /docs/misc